library(SGCB)

set.seed(12345)
G <- 1000L; n <- 6L
counts <- matrix(rnbinom(G * n, mu = 100, size = 5), nrow = G)
rownames(counts) <- paste0("gene", seq_len(G))
counts[1:100, 4:6] <- counts[1:100, 4:6] * 3L
group <- c(rep(0L, 3L), rep(1L, 3L))

cat("====== Test A: sgcbDReg two-group (3+3) ======\n")
t0 <- proc.time()
resD <- sgcbDReg(counts, group = group)
cat("time:", (proc.time() - t0)[3], "s\n")
cat("n_sig (padj<0.05):", sum(resD$padj < 0.05), "\n")
cat("TP:", sum(resD$padj[1:100] < 0.05), "FP:", sum(resD$padj[101:1000] < 0.05), "\n")
cat("lfc DE median:", round(median(resD$log2FoldChange[1:100]), 3), "\n")
cat("lfc null median:", round(median(resD$log2FoldChange[101:1000]), 3), "\n")

cat("\n====== Test B: sgcbDE two-group (3+3) ======\n")
t0 <- proc.time()
resE <- sgcbDE(counts, group)
cat("time:", (proc.time() - t0)[3], "s\n")
cat("n_sig (padj<0.05):", sum(resE$padj < 0.05), "\n")
cat("TP:", sum(resE$padj[1:100] < 0.05), "FP:", sum(resE$padj[101:1000] < 0.05), "\n")
cat("lfc DE median:", round(median(resE$log2FoldChange[1:100]), 3), "\n")
cat("lfc null median:", round(median(resE$log2FoldChange[101:1000]), 3), "\n")

cat("\n====== Test C: sgcbDReg with batch (3+3) ======\n")
batch <- c(1, 2, 1, 2, 1, 2)
design2 <- model.matrix(~ factor(group) + factor(batch))
resB <- sgcbDReg(counts, design = design2, contrast = c(0, 1, 0))
cat("n_sig:", sum(resB$padj < 0.05), "\n")
cat("TP:", sum(resB$padj[1:100] < 0.05), "FP:", sum(resB$padj[101:1000] < 0.05), "\n")

cat("\n====== Test D: sgcbDReg larger sample (10+10) ======\n")
set.seed(99)
G2 <- 2000L; n2 <- 20L
counts2 <- matrix(rnbinom(G2 * n2, mu = 80, size = 4), nrow = G2)
rownames(counts2) <- paste0("g", seq_len(G2))
counts2[1:200, 11:20] <- counts2[1:200, 11:20] * 2L
group2 <- c(rep(0L, 10L), rep(1L, 10L))
t0 <- proc.time()
resL <- sgcbDReg(counts2, group = group2)
cat("time:", (proc.time() - t0)[3], "s\n")
cat("n_sig:", sum(resL$padj < 0.05), "\n")
cat("TP:", sum(resL$padj[1:200] < 0.05), "FP:", sum(resL$padj[201:2000] < 0.05), "\n")
cat("alpha median:", round(median(resL$alpha), 2), "\n")
cat("gamma range:", round(range(resL$gamma), 3), "\n")
cat("df_total:", round(attr(resL, "df_total"), 1), "\n")

cat("\n====== Test E: lfc correlation DReg vs DE ======\n")
shared <- intersect(resD$gene_id, resE$gene_id)
m <- match(shared, resD$gene_id)
m2 <- match(shared, resE$gene_id)
r <- cor(resD$log2FoldChange[m], resE$log2FoldChange[m2])
cat("Pearson r(lfc):", round(r, 4), "\n")

cat("\n====== Test F: DV test (design_disp='auto') ======\n")
set.seed(42)
G3 <- 1000L; n3 <- 10L
ct3 <- matrix(rnbinom(G3 * n3, mu = 80, size = 5), nrow = G3)
rownames(ct3) <- paste0("dv", seq_len(G3))
ct3[1:100, 6:10] <- matrix(rnbinom(100L * 5L, mu = 80, size = 1), nrow = 100L)
group3 <- c(rep(0L, 5L), rep(1L, 5L))
t0 <- proc.time()
resV <- sgcbDReg(ct3, group = group3, design_disp = "auto")
cat("time:", (proc.time() - t0)[3], "s\n")
cat("ncol:", ncol(resV), "\n")
cat("method:", attr(resV, "method"), "\n")
cat("DV cols present:", all(c("pvalue_dv", "padj_dv", "dv_log2ratio") %in% names(resV)), "\n")
cat("\nDV genes (1:100) padj_dv < 0.05:", sum(resV$padj_dv[1:100] < 0.05), "\n")
cat("DV null (101:1000) padj_dv < 0.05:", sum(resV$padj_dv[101:1000] < 0.05), "\n")
cat("DV logratio DV-genes median:", round(median(resV$dv_log2ratio[1:100]), 3), "\n")
cat("DV logratio null median:", round(median(resV$dv_log2ratio[101:1000]), 3), "\n")
cat("LR stat DV-genes median:", round(median(resV$lr_stat_dv[1:100]), 3), "\n")
cat("LR stat null median:", round(median(resV$lr_stat_dv[101:1000]), 3), "\n")

cat("\nDone!\n")
