// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// shrink_lfc_normal
Rcpp::NumericVector shrink_lfc_normal(Rcpp::NumericVector lfc, Rcpp::NumericVector lfc_se, double prior_scale);
RcppExport SEXP _SGCB_shrink_lfc_normal(SEXP lfcSEXP, SEXP lfc_seSEXP, SEXP prior_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc(lfcSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc_se(lfc_seSEXP);
    Rcpp::traits::input_parameter< double >::type prior_scale(prior_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(shrink_lfc_normal(lfc, lfc_se, prior_scale));
    return rcpp_result_gen;
END_RCPP
}
// shrink_lfc_cauchy
Rcpp::NumericVector shrink_lfc_cauchy(Rcpp::NumericVector lfc, Rcpp::NumericVector lfc_se, double prior_scale);
RcppExport SEXP _SGCB_shrink_lfc_cauchy(SEXP lfcSEXP, SEXP lfc_seSEXP, SEXP prior_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc(lfcSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc_se(lfc_seSEXP);
    Rcpp::traits::input_parameter< double >::type prior_scale(prior_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(shrink_lfc_cauchy(lfc, lfc_se, prior_scale));
    return rcpp_result_gen;
END_RCPP
}
// tmm_factors_cpp
NumericVector tmm_factors_cpp(NumericMatrix counts, int ref_idx, double trim_m, double trim_a, double eps, int n_threads);
RcppExport SEXP _SGCB_tmm_factors_cpp(SEXP countsSEXP, SEXP ref_idxSEXP, SEXP trim_mSEXP, SEXP trim_aSEXP, SEXP epsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type ref_idx(ref_idxSEXP);
    Rcpp::traits::input_parameter< double >::type trim_m(trim_mSEXP);
    Rcpp::traits::input_parameter< double >::type trim_a(trim_aSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tmm_factors_cpp(counts, ref_idx, trim_m, trim_a, eps, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// row_quantiles_cpp
NumericMatrix row_quantiles_cpp(NumericMatrix X, NumericVector probs, int n_threads);
RcppExport SEXP _SGCB_row_quantiles_cpp(SEXP XSEXP, SEXP probsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(row_quantiles_cpp(X, probs, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// gg_loglik_vec
Rcpp::NumericVector gg_loglik_vec(const Rcpp::NumericVector& x, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& gamma, double eps);
RcppExport SEXP _SGCB_gg_loglik_vec(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_loglik_vec(x, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// gg_grad_params
Rcpp::NumericMatrix gg_grad_params(const Rcpp::NumericVector& x, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& gamma, double eps);
RcppExport SEXP _SGCB_gg_grad_params(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_grad_params(x, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// gg_hessian_diag
Rcpp::NumericMatrix gg_hessian_diag(Rcpp::NumericVector x, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, double eps);
RcppExport SEXP _SGCB_gg_hessian_diag(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_hessian_diag(x, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// gg_sample_mat
Rcpp::NumericMatrix gg_sample_mat(int n_genes, int n_samples, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, double eps);
RcppExport SEXP _SGCB_gg_sample_mat(SEXP n_genesSEXP, SEXP n_samplesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_sample_mat(n_genes, n_samples, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// fisher_info_diag
Rcpp::NumericMatrix fisher_info_diag(Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, int n_samples);
RcppExport SEXP _SGCB_fisher_info_diag(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_info_diag(alpha, beta, gamma, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// fisher_info_schur_ag
Rcpp::NumericMatrix fisher_info_schur_ag(Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, int n_samples);
RcppExport SEXP _SGCB_fisher_info_schur_ag(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_info_schur_ag(alpha, beta, gamma, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// fisher_info_full_inverse
Rcpp::NumericMatrix fisher_info_full_inverse(Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, int n_samples);
RcppExport SEXP _SGCB_fisher_info_full_inverse(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_info_full_inverse(alpha, beta, gamma, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_dreg_v1_cpp
List sgcb_dreg_v1_cpp(NumericMatrix y, NumericMatrix design, NumericVector contrast, int max_outer, int max_inner_ag, double ag_lr, double tol, double eps);
RcppExport SEXP _SGCB_sgcb_dreg_v1_cpp(SEXP ySEXP, SEXP designSEXP, SEXP contrastSEXP, SEXP max_outerSEXP, SEXP max_inner_agSEXP, SEXP ag_lrSEXP, SEXP tolSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type contrast(contrastSEXP);
    Rcpp::traits::input_parameter< int >::type max_outer(max_outerSEXP);
    Rcpp::traits::input_parameter< int >::type max_inner_ag(max_inner_agSEXP);
    Rcpp::traits::input_parameter< double >::type ag_lr(ag_lrSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_dreg_v1_cpp(y, design, contrast, max_outer, max_inner_ag, ag_lr, tol, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_dreg_dv_cpp
List sgcb_dreg_dv_cpp(NumericMatrix y, NumericMatrix design_mean, NumericMatrix design_disp, NumericVector contrast_disp, NumericMatrix coef_v1, NumericVector alpha_v1, NumericVector gamma_v1, int max_outer_dv, int max_inner_d, double d_lr, double eps);
RcppExport SEXP _SGCB_sgcb_dreg_dv_cpp(SEXP ySEXP, SEXP design_meanSEXP, SEXP design_dispSEXP, SEXP contrast_dispSEXP, SEXP coef_v1SEXP, SEXP alpha_v1SEXP, SEXP gamma_v1SEXP, SEXP max_outer_dvSEXP, SEXP max_inner_dSEXP, SEXP d_lrSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type design_mean(design_meanSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type design_disp(design_dispSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type contrast_disp(contrast_dispSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type coef_v1(coef_v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_v1(alpha_v1SEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_v1(gamma_v1SEXP);
    Rcpp::traits::input_parameter< int >::type max_outer_dv(max_outer_dvSEXP);
    Rcpp::traits::input_parameter< int >::type max_inner_d(max_inner_dSEXP);
    Rcpp::traits::input_parameter< double >::type d_lr(d_lrSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_dreg_dv_cpp(y, design_mean, design_disp, contrast_disp, coef_v1, alpha_v1, gamma_v1, max_outer_dv, max_inner_d, d_lr, eps));
    return rcpp_result_gen;
END_RCPP
}
// fit_gg_natural_gradient_cpp
List fit_gg_natural_gradient_cpp(NumericMatrix X, int n_iter, double lr, double weight_decay, bool use_natural_grad, bool use_firth_override, bool use_gamma_submodel, double eps);
RcppExport SEXP _SGCB_fit_gg_natural_gradient_cpp(SEXP XSEXP, SEXP n_iterSEXP, SEXP lrSEXP, SEXP weight_decaySEXP, SEXP use_natural_gradSEXP, SEXP use_firth_overrideSEXP, SEXP use_gamma_submodelSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type weight_decay(weight_decaySEXP);
    Rcpp::traits::input_parameter< bool >::type use_natural_grad(use_natural_gradSEXP);
    Rcpp::traits::input_parameter< bool >::type use_firth_override(use_firth_overrideSEXP);
    Rcpp::traits::input_parameter< bool >::type use_gamma_submodel(use_gamma_submodelSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gg_natural_gradient_cpp(X, n_iter, lr, weight_decay, use_natural_grad, use_firth_override, use_gamma_submodel, eps));
    return rcpp_result_gen;
END_RCPP
}
// fit_gg_profile_init_cpp
List fit_gg_profile_init_cpp(NumericMatrix X, bool use_gamma_submodel, double min_gamma, double max_gamma, double eps);
RcppExport SEXP _SGCB_fit_gg_profile_init_cpp(SEXP XSEXP, SEXP use_gamma_submodelSEXP, SEXP min_gammaSEXP, SEXP max_gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type use_gamma_submodel(use_gamma_submodelSEXP);
    Rcpp::traits::input_parameter< double >::type min_gamma(min_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type max_gamma(max_gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gg_profile_init_cpp(X, use_gamma_submodel, min_gamma, max_gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// fit_gg_hierarchical_bayes_cpp
List fit_gg_hierarchical_bayes_cpp(NumericMatrix X, int n_iter, double lr, double prior_strength, bool use_natural_grad, double eps);
RcppExport SEXP _SGCB_fit_gg_hierarchical_bayes_cpp(SEXP XSEXP, SEXP n_iterSEXP, SEXP lrSEXP, SEXP prior_strengthSEXP, SEXP use_natural_gradSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type prior_strength(prior_strengthSEXP);
    Rcpp::traits::input_parameter< bool >::type use_natural_grad(use_natural_gradSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gg_hierarchical_bayes_cpp(X, n_iter, lr, prior_strength, use_natural_grad, eps));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_squeeze_var_gg_informed_cpp
List adaptive_squeeze_var_gg_informed_cpp(NumericVector vars, NumericVector gg_alpha, NumericVector gg_beta, NumericVector gg_gamma, int n_samples, double eps);
RcppExport SEXP _SGCB_adaptive_squeeze_var_gg_informed_cpp(SEXP varsSEXP, SEXP gg_alphaSEXP, SEXP gg_betaSEXP, SEXP gg_gammaSEXP, SEXP n_samplesSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gg_alpha(gg_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gg_beta(gg_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gg_gamma(gg_gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_squeeze_var_gg_informed_cpp(vars, gg_alpha, gg_beta, gg_gamma, n_samples, eps));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_squeeze_var_hierarchical_cpp
List adaptive_squeeze_var_hierarchical_cpp(NumericVector vars, NumericVector gene_means, int n_samples, bool use_rff_trend, double eps);
RcppExport SEXP _SGCB_adaptive_squeeze_var_hierarchical_cpp(SEXP varsSEXP, SEXP gene_meansSEXP, SEXP n_samplesSEXP, SEXP use_rff_trendSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gene_means(gene_meansSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< bool >::type use_rff_trend(use_rff_trendSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_squeeze_var_hierarchical_cpp(vars, gene_means, n_samples, use_rff_trend, eps));
    return rcpp_result_gen;
END_RCPP
}
// manifold_distance_test_cpp
List manifold_distance_test_cpp(NumericVector alpha_ctrl, NumericVector beta_ctrl, NumericVector gamma_ctrl, NumericVector alpha_treat, NumericVector beta_treat, NumericVector gamma_treat, int n_ctrl, int n_treat, double eps);
RcppExport SEXP _SGCB_manifold_distance_test_cpp(SEXP alpha_ctrlSEXP, SEXP beta_ctrlSEXP, SEXP gamma_ctrlSEXP, SEXP alpha_treatSEXP, SEXP beta_treatSEXP, SEXP gamma_treatSEXP, SEXP n_ctrlSEXP, SEXP n_treatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type alpha_ctrl(alpha_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_ctrl(beta_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_ctrl(gamma_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_treat(alpha_treatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_treat(beta_treatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_treat(gamma_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctrl(n_ctrlSEXP);
    Rcpp::traits::input_parameter< int >::type n_treat(n_treatSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_distance_test_cpp(alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_wls_ebayes_cpp
List sgcb_wls_ebayes_cpp(NumericMatrix y, NumericMatrix design, NumericVector contrast, NumericVector gene_means, NumericVector weights, double eps);
RcppExport SEXP _SGCB_sgcb_wls_ebayes_cpp(SEXP ySEXP, SEXP designSEXP, SEXP contrastSEXP, SEXP gene_meansSEXP, SEXP weightsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type contrast(contrastSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gene_means(gene_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_wls_ebayes_cpp(y, design, contrast, gene_means, weights, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_info_geom_inference_cpp
List sgcb_info_geom_inference_cpp(NumericMatrix X, IntegerVector group, int n_dropout, double dropout_rate, bool use_natural_grad, bool use_hierarchical, bool use_firth, bool use_gamma_submodel, bool use_gg_variance, double eps);
RcppExport SEXP _SGCB_sgcb_info_geom_inference_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP use_natural_gradSEXP, SEXP use_hierarchicalSEXP, SEXP use_firthSEXP, SEXP use_gamma_submodelSEXP, SEXP use_gg_varianceSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type use_natural_grad(use_natural_gradSEXP);
    Rcpp::traits::input_parameter< bool >::type use_hierarchical(use_hierarchicalSEXP);
    Rcpp::traits::input_parameter< bool >::type use_firth(use_firthSEXP);
    Rcpp::traits::input_parameter< bool >::type use_gamma_submodel(use_gamma_submodelSEXP);
    Rcpp::traits::input_parameter< bool >::type use_gg_variance(use_gg_varianceSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_info_geom_inference_cpp(X, group, n_dropout, dropout_rate, use_natural_grad, use_hierarchical, use_firth, use_gamma_submodel, use_gg_variance, eps));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SGCB_shrink_lfc_normal", (DL_FUNC) &_SGCB_shrink_lfc_normal, 3},
    {"_SGCB_shrink_lfc_cauchy", (DL_FUNC) &_SGCB_shrink_lfc_cauchy, 3},
    {"_SGCB_tmm_factors_cpp", (DL_FUNC) &_SGCB_tmm_factors_cpp, 6},
    {"_SGCB_row_quantiles_cpp", (DL_FUNC) &_SGCB_row_quantiles_cpp, 3},
    {"_SGCB_gg_loglik_vec", (DL_FUNC) &_SGCB_gg_loglik_vec, 5},
    {"_SGCB_gg_grad_params", (DL_FUNC) &_SGCB_gg_grad_params, 5},
    {"_SGCB_gg_hessian_diag", (DL_FUNC) &_SGCB_gg_hessian_diag, 5},
    {"_SGCB_gg_sample_mat", (DL_FUNC) &_SGCB_gg_sample_mat, 6},
    {"_SGCB_fisher_info_diag", (DL_FUNC) &_SGCB_fisher_info_diag, 4},
    {"_SGCB_fisher_info_schur_ag", (DL_FUNC) &_SGCB_fisher_info_schur_ag, 4},
    {"_SGCB_fisher_info_full_inverse", (DL_FUNC) &_SGCB_fisher_info_full_inverse, 4},
    {"_SGCB_sgcb_dreg_v1_cpp", (DL_FUNC) &_SGCB_sgcb_dreg_v1_cpp, 8},
    {"_SGCB_sgcb_dreg_dv_cpp", (DL_FUNC) &_SGCB_sgcb_dreg_dv_cpp, 11},
    {"_SGCB_fit_gg_natural_gradient_cpp", (DL_FUNC) &_SGCB_fit_gg_natural_gradient_cpp, 8},
    {"_SGCB_fit_gg_profile_init_cpp", (DL_FUNC) &_SGCB_fit_gg_profile_init_cpp, 5},
    {"_SGCB_fit_gg_hierarchical_bayes_cpp", (DL_FUNC) &_SGCB_fit_gg_hierarchical_bayes_cpp, 6},
    {"_SGCB_adaptive_squeeze_var_gg_informed_cpp", (DL_FUNC) &_SGCB_adaptive_squeeze_var_gg_informed_cpp, 6},
    {"_SGCB_adaptive_squeeze_var_hierarchical_cpp", (DL_FUNC) &_SGCB_adaptive_squeeze_var_hierarchical_cpp, 5},
    {"_SGCB_manifold_distance_test_cpp", (DL_FUNC) &_SGCB_manifold_distance_test_cpp, 9},
    {"_SGCB_sgcb_wls_ebayes_cpp", (DL_FUNC) &_SGCB_sgcb_wls_ebayes_cpp, 6},
    {"_SGCB_sgcb_info_geom_inference_cpp", (DL_FUNC) &_SGCB_sgcb_info_geom_inference_cpp, 10},
    {NULL, NULL, 0}
};

RcppExport void R_init_SGCB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
