// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// adaptive_squeeze_var_cpp
List adaptive_squeeze_var_cpp(NumericVector var, int df, int n_samples, double eps);
RcppExport SEXP _SGCB_adaptive_squeeze_var_cpp(SEXP varSEXP, SEXP dfSEXP, SEXP n_samplesSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type var(varSEXP);
    Rcpp::traits::input_parameter< int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_squeeze_var_cpp(var, df, n_samples, eps));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_moderated_t_cpp
List adaptive_moderated_t_cpp(NumericMatrix X, IntegerVector group, NumericVector ae_alpha, NumericVector ae_beta, NumericVector ae_gamma, NumericVector stability, double eps);
RcppExport SEXP _SGCB_adaptive_moderated_t_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP ae_alphaSEXP, SEXP ae_betaSEXP, SEXP ae_gammaSEXP, SEXP stabilitySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_alpha(ae_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_beta(ae_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_gamma(ae_gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stability(stabilitySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_moderated_t_cpp(X, group, ae_alpha, ae_beta, ae_gamma, stability, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_adaptive_inference_cpp
List sgcb_adaptive_inference_cpp(NumericMatrix X, IntegerVector group, NumericVector ae_alpha, NumericVector ae_beta, NumericVector ae_gamma, NumericVector lfc_stable, NumericVector lfc_var, NumericVector stability, double eps);
RcppExport SEXP _SGCB_sgcb_adaptive_inference_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP ae_alphaSEXP, SEXP ae_betaSEXP, SEXP ae_gammaSEXP, SEXP lfc_stableSEXP, SEXP lfc_varSEXP, SEXP stabilitySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_alpha(ae_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_beta(ae_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_gamma(ae_gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lfc_stable(lfc_stableSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lfc_var(lfc_varSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stability(stabilitySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_adaptive_inference_cpp(X, group, ae_alpha, ae_beta, ae_gamma, lfc_stable, lfc_var, stability, eps));
    return rcpp_result_gen;
END_RCPP
}
// resample_indices
Rcpp::IntegerMatrix resample_indices(int n, int m, int B, int seed);
RcppExport SEXP _SGCB_resample_indices(SEXP nSEXP, SEXP mSEXP, SEXP BSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(resample_indices(n, m, B, seed));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_resample
Rcpp::NumericMatrix bootstrap_resample(Rcpp::NumericMatrix X, Rcpp::IntegerVector indices);
RcppExport SEXP _SGCB_bootstrap_resample(SEXP XSEXP, SEXP indicesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::IntegerVector >::type indices(indicesSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_resample(X, indices));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_mean
Rcpp::NumericVector bootstrap_mean(Rcpp::NumericMatrix X, int B, int seed);
RcppExport SEXP _SGCB_bootstrap_mean(SEXP XSEXP, SEXP BSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_mean(X, B, seed));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_gene_stats
Rcpp::NumericMatrix bootstrap_gene_stats(const Rcpp::NumericMatrix& X, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& gamma, int m, int B, double eps, int seed);
RcppExport SEXP _SGCB_bootstrap_gene_stats(SEXP XSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP mSEXP, SEXP BSEXP, SEXP epsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< int >::type B(BSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_gene_stats(X, alpha, beta, gamma, m, B, eps, seed));
    return rcpp_result_gen;
END_RCPP
}
// calibrated_bootstrap_search
Rcpp::List calibrated_bootstrap_search(Rcpp::NumericMatrix X, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, Rcpp::NumericVector T_obs, Rcpp::NumericVector m_fracs, int cb_reps, double target_coverage, double eps, int seed);
RcppExport SEXP _SGCB_calibrated_bootstrap_search(SEXP XSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP T_obsSEXP, SEXP m_fracsSEXP, SEXP cb_repsSEXP, SEXP target_coverageSEXP, SEXP epsSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m_fracs(m_fracsSEXP);
    Rcpp::traits::input_parameter< int >::type cb_reps(cb_repsSEXP);
    Rcpp::traits::input_parameter< double >::type target_coverage(target_coverageSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(calibrated_bootstrap_search(X, alpha, beta, gamma, T_obs, m_fracs, cb_reps, target_coverage, eps, seed));
    return rcpp_result_gen;
END_RCPP
}
// permutation_pvalues
Rcpp::NumericVector permutation_pvalues(Rcpp::NumericVector T_obs, Rcpp::NumericMatrix T_null);
RcppExport SEXP _SGCB_permutation_pvalues(SEXP T_obsSEXP, SEXP T_nullSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type T_null(T_nullSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_pvalues(T_obs, T_null));
    return rcpp_result_gen;
END_RCPP
}
// bootstrap_confidence_intervals
Rcpp::NumericMatrix bootstrap_confidence_intervals(const Rcpp::NumericMatrix& T_null, double alpha);
RcppExport SEXP _SGCB_bootstrap_confidence_intervals(SEXP T_nullSEXP, SEXP alphaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type T_null(T_nullSEXP);
    Rcpp::traits::input_parameter< double >::type alpha(alphaSEXP);
    rcpp_result_gen = Rcpp::wrap(bootstrap_confidence_intervals(T_null, alpha));
    return rcpp_result_gen;
END_RCPP
}
// bh_adjust
Rcpp::NumericVector bh_adjust(Rcpp::NumericVector pvals);
RcppExport SEXP _SGCB_bh_adjust(SEXP pvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pvals(pvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(bh_adjust(pvals));
    return rcpp_result_gen;
END_RCPP
}
// bonferroni_adjust
Rcpp::NumericVector bonferroni_adjust(Rcpp::NumericVector pvals);
RcppExport SEXP _SGCB_bonferroni_adjust(SEXP pvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pvals(pvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(bonferroni_adjust(pvals));
    return rcpp_result_gen;
END_RCPP
}
// holm_adjust
Rcpp::NumericVector holm_adjust(Rcpp::NumericVector pvals);
RcppExport SEXP _SGCB_holm_adjust(SEXP pvalsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type pvals(pvalsSEXP);
    rcpp_result_gen = Rcpp::wrap(holm_adjust(pvals));
    return rcpp_result_gen;
END_RCPP
}
// effect_sizes
Rcpp::List effect_sizes(Rcpp::NumericMatrix control, Rcpp::NumericMatrix treat, double eps);
RcppExport SEXP _SGCB_effect_sizes(SEXP controlSEXP, SEXP treatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type control(controlSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type treat(treatSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(effect_sizes(control, treat, eps));
    return rcpp_result_gen;
END_RCPP
}
// shrink_lfc_normal
Rcpp::NumericVector shrink_lfc_normal(Rcpp::NumericVector lfc, Rcpp::NumericVector lfc_se, double prior_scale);
RcppExport SEXP _SGCB_shrink_lfc_normal(SEXP lfcSEXP, SEXP lfc_seSEXP, SEXP prior_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc(lfcSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc_se(lfc_seSEXP);
    Rcpp::traits::input_parameter< double >::type prior_scale(prior_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(shrink_lfc_normal(lfc, lfc_se, prior_scale));
    return rcpp_result_gen;
END_RCPP
}
// shrink_lfc_cauchy
Rcpp::NumericVector shrink_lfc_cauchy(Rcpp::NumericVector lfc, Rcpp::NumericVector lfc_se, double prior_scale);
RcppExport SEXP _SGCB_shrink_lfc_cauchy(SEXP lfcSEXP, SEXP lfc_seSEXP, SEXP prior_scaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc(lfcSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type lfc_se(lfc_seSEXP);
    Rcpp::traits::input_parameter< double >::type prior_scale(prior_scaleSEXP);
    rcpp_result_gen = Rcpp::wrap(shrink_lfc_cauchy(lfc, lfc_se, prior_scale));
    return rcpp_result_gen;
END_RCPP
}
// calibrated_bootstrap_gene_cpp
List calibrated_bootstrap_gene_cpp(NumericVector x_ctrl, NumericVector x_treat, int n_boot, double m_ratio, int seed);
RcppExport SEXP _SGCB_calibrated_bootstrap_gene_cpp(SEXP x_ctrlSEXP, SEXP x_treatSEXP, SEXP n_bootSEXP, SEXP m_ratioSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x_ctrl(x_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type x_treat(x_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type m_ratio(m_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(calibrated_bootstrap_gene_cpp(x_ctrl, x_treat, n_boot, m_ratio, seed));
    return rcpp_result_gen;
END_RCPP
}
// calibrated_bootstrap_all_cpp
List calibrated_bootstrap_all_cpp(NumericMatrix X, IntegerVector group, int n_boot, double m_ratio, int seed);
RcppExport SEXP _SGCB_calibrated_bootstrap_all_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_bootSEXP, SEXP m_ratioSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type m_ratio(m_ratioSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(calibrated_bootstrap_all_cpp(X, group, n_boot, m_ratio, seed));
    return rcpp_result_gen;
END_RCPP
}
// gg_mle_single_cpp
List gg_mle_single_cpp(NumericVector x, int max_iter, double tol);
RcppExport SEXP _SGCB_gg_mle_single_cpp(SEXP xSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_mle_single_cpp(x, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// gg_mle_all_cpp
List gg_mle_all_cpp(NumericMatrix X, int max_iter, double tol);
RcppExport SEXP _SGCB_gg_mle_all_cpp(SEXP XSEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_mle_all_cpp(X, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// fit_conditional_ae_cpp
List fit_conditional_ae_cpp(NumericMatrix X, IntegerVector batch, IntegerVector condition, int n_iter, int h_ratio, double lr, double eps);
RcppExport SEXP _SGCB_fit_conditional_ae_cpp(SEXP XSEXP, SEXP batchSEXP, SEXP conditionSEXP, SEXP n_iterSEXP, SEXP h_ratioSEXP, SEXP lrSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type condition(conditionSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type h_ratio(h_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_conditional_ae_cpp(X, batch, condition, n_iter, h_ratio, lr, eps));
    return rcpp_result_gen;
END_RCPP
}
// conditional_de_test_cpp
List conditional_de_test_cpp(NumericMatrix X, IntegerVector batch, IntegerVector condition, NumericMatrix alpha, NumericMatrix beta, NumericMatrix gamma, NumericMatrix batch_effect, int cond_ctrl, int cond_treat, int n_boot, double eps);
RcppExport SEXP _SGCB_conditional_de_test_cpp(SEXP XSEXP, SEXP batchSEXP, SEXP conditionSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP batch_effectSEXP, SEXP cond_ctrlSEXP, SEXP cond_treatSEXP, SEXP n_bootSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type condition(conditionSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type batch_effect(batch_effectSEXP);
    Rcpp::traits::input_parameter< int >::type cond_ctrl(cond_ctrlSEXP);
    Rcpp::traits::input_parameter< int >::type cond_treat(cond_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(conditional_de_test_cpp(X, batch, condition, alpha, beta, gamma, batch_effect, cond_ctrl, cond_treat, n_boot, eps));
    return rcpp_result_gen;
END_RCPP
}
// remove_batch_effect_cpp
NumericMatrix remove_batch_effect_cpp(NumericMatrix X, IntegerVector batch, NumericMatrix batch_effect);
RcppExport SEXP _SGCB_remove_batch_effect_cpp(SEXP XSEXP, SEXP batchSEXP, SEXP batch_effectSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type batch(batchSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type batch_effect(batch_effectSEXP);
    rcpp_result_gen = Rcpp::wrap(remove_batch_effect_cpp(X, batch, batch_effect));
    return rcpp_result_gen;
END_RCPP
}
// local_weighted_regression_cpp
NumericVector local_weighted_regression_cpp(const NumericVector& x, const NumericVector& y, double span, int n_threads);
RcppExport SEXP _SGCB_local_weighted_regression_cpp(SEXP xSEXP, SEXP ySEXP, SEXP spanSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const NumericVector& >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type span(spanSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(local_weighted_regression_cpp(x, y, span, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// column_medians_cpp
NumericVector column_medians_cpp(const NumericMatrix& X, int n_threads);
RcppExport SEXP _SGCB_column_medians_cpp(SEXP XSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(column_medians_cpp(X, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// row_medians_cpp
NumericVector row_medians_cpp(const NumericMatrix& X, int n_threads);
RcppExport SEXP _SGCB_row_medians_cpp(SEXP XSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(row_medians_cpp(X, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// tmm_factors_cpp
NumericVector tmm_factors_cpp(NumericMatrix counts, int ref_idx, double trim_m, double trim_a, double eps, int n_threads);
RcppExport SEXP _SGCB_tmm_factors_cpp(SEXP countsSEXP, SEXP ref_idxSEXP, SEXP trim_mSEXP, SEXP trim_aSEXP, SEXP epsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< int >::type ref_idx(ref_idxSEXP);
    Rcpp::traits::input_parameter< double >::type trim_m(trim_mSEXP);
    Rcpp::traits::input_parameter< double >::type trim_a(trim_aSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(tmm_factors_cpp(counts, ref_idx, trim_m, trim_a, eps, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// fit_dispersion_trend_parametric_cpp
List fit_dispersion_trend_parametric_cpp(NumericVector means, NumericVector dispersions, double eps);
RcppExport SEXP _SGCB_fit_dispersion_trend_parametric_cpp(SEXP meansSEXP, SEXP dispersionsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type means(meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dispersions(dispersionsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_dispersion_trend_parametric_cpp(means, dispersions, eps));
    return rcpp_result_gen;
END_RCPP
}
// estimate_disp_tagwise_cpp
List estimate_disp_tagwise_cpp(NumericMatrix counts, double span, double prior_df, double eps, int n_threads);
RcppExport SEXP _SGCB_estimate_disp_tagwise_cpp(SEXP countsSEXP, SEXP spanSEXP, SEXP prior_dfSEXP, SEXP epsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type counts(countsSEXP);
    Rcpp::traits::input_parameter< double >::type span(spanSEXP);
    Rcpp::traits::input_parameter< double >::type prior_df(prior_dfSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(estimate_disp_tagwise_cpp(counts, span, prior_df, eps, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// row_quantiles_cpp
NumericMatrix row_quantiles_cpp(NumericMatrix X, NumericVector probs, int n_threads);
RcppExport SEXP _SGCB_row_quantiles_cpp(SEXP XSEXP, SEXP probsSEXP, SEXP n_threadsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type probs(probsSEXP);
    Rcpp::traits::input_parameter< int >::type n_threads(n_threadsSEXP);
    rcpp_result_gen = Rcpp::wrap(row_quantiles_cpp(X, probs, n_threads));
    return rcpp_result_gen;
END_RCPP
}
// gg_loglik_vec
Rcpp::NumericVector gg_loglik_vec(const Rcpp::NumericVector& x, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& gamma, double eps);
RcppExport SEXP _SGCB_gg_loglik_vec(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_loglik_vec(x, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// gg_grad_params
Rcpp::NumericMatrix gg_grad_params(const Rcpp::NumericVector& x, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& gamma, double eps);
RcppExport SEXP _SGCB_gg_grad_params(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_grad_params(x, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// gg_hessian_diag
Rcpp::NumericMatrix gg_hessian_diag(Rcpp::NumericVector x, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, double eps);
RcppExport SEXP _SGCB_gg_hessian_diag(SEXP xSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_hessian_diag(x, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// gg_sample_mat
Rcpp::NumericMatrix gg_sample_mat(int n_genes, int n_samples, Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, double eps);
RcppExport SEXP _SGCB_gg_sample_mat(SEXP n_genesSEXP, SEXP n_samplesSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(gg_sample_mat(n_genes, n_samples, alpha, beta, gamma, eps));
    return rcpp_result_gen;
END_RCPP
}
// clip_value
double clip_value(double x, double lo, double hi);
RcppExport SEXP _SGCB_clip_value(SEXP xSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(clip_value(x, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// clip_vec
Rcpp::NumericVector clip_vec(Rcpp::NumericVector x, double lo, double hi);
RcppExport SEXP _SGCB_clip_vec(SEXP xSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(clip_vec(x, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// adam_update
Rcpp::List adam_update(Rcpp::NumericVector param, Rcpp::NumericVector grad, Rcpp::NumericVector m, Rcpp::NumericVector v, double lr, double beta1, double beta2, double eps, int t);
RcppExport SEXP _SGCB_adam_update(SEXP paramSEXP, SEXP gradSEXP, SEXP mSEXP, SEXP vSEXP, SEXP lrSEXP, SEXP beta1SEXP, SEXP beta2SEXP, SEXP epsSEXP, SEXP tSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type param(paramSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type grad(gradSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type m(mSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type v(vSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type beta1(beta1SEXP);
    Rcpp::traits::input_parameter< double >::type beta2(beta2SEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< int >::type t(tSEXP);
    rcpp_result_gen = Rcpp::wrap(adam_update(param, grad, m, v, lr, beta1, beta2, eps, t));
    return rcpp_result_gen;
END_RCPP
}
// softplus_mat
Rcpp::NumericMatrix softplus_mat(Rcpp::NumericMatrix x, double threshold);
RcppExport SEXP _SGCB_softplus_mat(SEXP xSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(softplus_mat(x, threshold));
    return rcpp_result_gen;
END_RCPP
}
// softplus_grad_mat
Rcpp::NumericMatrix softplus_grad_mat(Rcpp::NumericMatrix x, double threshold);
RcppExport SEXP _SGCB_softplus_grad_mat(SEXP xSEXP, SEXP thresholdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type threshold(thresholdSEXP);
    rcpp_result_gen = Rcpp::wrap(softplus_grad_mat(x, threshold));
    return rcpp_result_gen;
END_RCPP
}
// clip_mat
Rcpp::NumericMatrix clip_mat(Rcpp::NumericMatrix x, double lo, double hi);
RcppExport SEXP _SGCB_clip_mat(SEXP xSEXP, SEXP loSEXP, SEXP hiSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type lo(loSEXP);
    Rcpp::traits::input_parameter< double >::type hi(hiSEXP);
    rcpp_result_gen = Rcpp::wrap(clip_mat(x, lo, hi));
    return rcpp_result_gen;
END_RCPP
}
// fisher_info_diag
Rcpp::NumericMatrix fisher_info_diag(Rcpp::NumericVector alpha, Rcpp::NumericVector beta, Rcpp::NumericVector gamma, int n_samples);
RcppExport SEXP _SGCB_fisher_info_diag(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_samplesSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    rcpp_result_gen = Rcpp::wrap(fisher_info_diag(alpha, beta, gamma, n_samples));
    return rcpp_result_gen;
END_RCPP
}
// compute_lfc
Rcpp::List compute_lfc(Rcpp::NumericVector treat_mean, Rcpp::NumericVector control_mean, Rcpp::NumericVector treat_var, Rcpp::NumericVector control_var, int n_treat, int n_control, double eps);
RcppExport SEXP _SGCB_compute_lfc(SEXP treat_meanSEXP, SEXP control_meanSEXP, SEXP treat_varSEXP, SEXP control_varSEXP, SEXP n_treatSEXP, SEXP n_controlSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type treat_mean(treat_meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_mean(control_meanSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type treat_var(treat_varSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type control_var(control_varSEXP);
    Rcpp::traits::input_parameter< int >::type n_treat(n_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_control(n_controlSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_lfc(treat_mean, control_mean, treat_var, control_var, n_treat, n_control, eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_T_stat_batch
Rcpp::NumericMatrix compute_T_stat_batch(const Rcpp::NumericMatrix& X, const Rcpp::NumericVector& alpha, const Rcpp::NumericVector& beta, const Rcpp::NumericVector& gamma, int n_genes, int n_samples, int n_batches, int batch_size, double eps);
RcppExport SEXP _SGCB_compute_T_stat_batch(SEXP XSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_genesSEXP, SEXP n_samplesSEXP, SEXP n_batchesSEXP, SEXP batch_sizeSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type n_batches(n_batchesSEXP);
    Rcpp::traits::input_parameter< int >::type batch_size(batch_sizeSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_T_stat_batch(X, alpha, beta, gamma, n_genes, n_samples, n_batches, batch_size, eps));
    return rcpp_result_gen;
END_RCPP
}
// compute_coverage_error
double compute_coverage_error(Rcpp::NumericMatrix T_null_mat, Rcpp::NumericVector T_obs, double target_coverage);
RcppExport SEXP _SGCB_compute_coverage_error(SEXP T_null_matSEXP, SEXP T_obsSEXP, SEXP target_coverageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type T_null_mat(T_null_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< double >::type target_coverage(target_coverageSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_coverage_error(T_null_mat, T_obs, target_coverage));
    return rcpp_result_gen;
END_RCPP
}
// compute_empirical_pvalues
Rcpp::NumericVector compute_empirical_pvalues(Rcpp::NumericMatrix T_null_mat, Rcpp::NumericVector T_obs);
RcppExport SEXP _SGCB_compute_empirical_pvalues(SEXP T_null_matSEXP, SEXP T_obsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type T_null_mat(T_null_matSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type T_obs(T_obsSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_empirical_pvalues(T_null_mat, T_obs));
    return rcpp_result_gen;
END_RCPP
}
// fit_gg_natural_gradient_cpp
List fit_gg_natural_gradient_cpp(NumericMatrix X, int n_iter, double lr, double weight_decay, bool use_natural_grad, double eps);
RcppExport SEXP _SGCB_fit_gg_natural_gradient_cpp(SEXP XSEXP, SEXP n_iterSEXP, SEXP lrSEXP, SEXP weight_decaySEXP, SEXP use_natural_gradSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type weight_decay(weight_decaySEXP);
    Rcpp::traits::input_parameter< bool >::type use_natural_grad(use_natural_gradSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gg_natural_gradient_cpp(X, n_iter, lr, weight_decay, use_natural_grad, eps));
    return rcpp_result_gen;
END_RCPP
}
// fit_gg_hierarchical_bayes_cpp
List fit_gg_hierarchical_bayes_cpp(NumericMatrix X, int n_iter, double lr, double prior_strength, bool use_natural_grad, double eps);
RcppExport SEXP _SGCB_fit_gg_hierarchical_bayes_cpp(SEXP XSEXP, SEXP n_iterSEXP, SEXP lrSEXP, SEXP prior_strengthSEXP, SEXP use_natural_gradSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type prior_strength(prior_strengthSEXP);
    Rcpp::traits::input_parameter< bool >::type use_natural_grad(use_natural_gradSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gg_hierarchical_bayes_cpp(X, n_iter, lr, prior_strength, use_natural_grad, eps));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_squeeze_var_gg_informed_cpp
List adaptive_squeeze_var_gg_informed_cpp(NumericVector vars, NumericVector gg_alpha, NumericVector gg_beta, NumericVector gg_gamma, int n_samples, double eps);
RcppExport SEXP _SGCB_adaptive_squeeze_var_gg_informed_cpp(SEXP varsSEXP, SEXP gg_alphaSEXP, SEXP gg_betaSEXP, SEXP gg_gammaSEXP, SEXP n_samplesSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gg_alpha(gg_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gg_beta(gg_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gg_gamma(gg_gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_squeeze_var_gg_informed_cpp(vars, gg_alpha, gg_beta, gg_gamma, n_samples, eps));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_squeeze_var_hierarchical_cpp
List adaptive_squeeze_var_hierarchical_cpp(NumericVector vars, NumericVector gene_means, int n_samples, double eps);
RcppExport SEXP _SGCB_adaptive_squeeze_var_hierarchical_cpp(SEXP varsSEXP, SEXP gene_meansSEXP, SEXP n_samplesSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gene_means(gene_meansSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_squeeze_var_hierarchical_cpp(vars, gene_means, n_samples, eps));
    return rcpp_result_gen;
END_RCPP
}
// manifold_distance_test_cpp
List manifold_distance_test_cpp(NumericVector alpha_ctrl, NumericVector beta_ctrl, NumericVector gamma_ctrl, NumericVector alpha_treat, NumericVector beta_treat, NumericVector gamma_treat, int n_ctrl, int n_treat, double eps);
RcppExport SEXP _SGCB_manifold_distance_test_cpp(SEXP alpha_ctrlSEXP, SEXP beta_ctrlSEXP, SEXP gamma_ctrlSEXP, SEXP alpha_treatSEXP, SEXP beta_treatSEXP, SEXP gamma_treatSEXP, SEXP n_ctrlSEXP, SEXP n_treatSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type alpha_ctrl(alpha_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_ctrl(beta_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_ctrl(gamma_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_treat(alpha_treatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_treat(beta_treatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_treat(gamma_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctrl(n_ctrlSEXP);
    Rcpp::traits::input_parameter< int >::type n_treat(n_treatSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(manifold_distance_test_cpp(alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_wls_ebayes_cpp
List sgcb_wls_ebayes_cpp(NumericMatrix y, NumericMatrix design, NumericVector contrast, NumericVector gene_means, NumericVector weights, double eps);
RcppExport SEXP _SGCB_sgcb_wls_ebayes_cpp(SEXP ySEXP, SEXP designSEXP, SEXP contrastSEXP, SEXP gene_meansSEXP, SEXP weightsSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type y(ySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type design(designSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type contrast(contrastSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gene_means(gene_meansSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type weights(weightsSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_wls_ebayes_cpp(y, design, contrast, gene_means, weights, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_info_geom_inference_cpp
List sgcb_info_geom_inference_cpp(NumericMatrix X, IntegerVector group, int n_dropout, double dropout_rate, bool use_natural_grad, bool use_hierarchical, double eps);
RcppExport SEXP _SGCB_sgcb_info_geom_inference_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP use_natural_gradSEXP, SEXP use_hierarchicalSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< bool >::type use_natural_grad(use_natural_gradSEXP);
    Rcpp::traits::input_parameter< bool >::type use_hierarchical(use_hierarchicalSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_info_geom_inference_cpp(X, group, n_dropout, dropout_rate, use_natural_grad, use_hierarchical, eps));
    return rcpp_result_gen;
END_RCPP
}
// matmul_parallel
Rcpp::NumericMatrix matmul_parallel(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B);
RcppExport SEXP _SGCB_matmul_parallel(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(matmul_parallel(A, B));
    return rcpp_result_gen;
END_RCPP
}
// tcrossprod_parallel
Rcpp::NumericMatrix tcrossprod_parallel(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B);
RcppExport SEXP _SGCB_tcrossprod_parallel(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(tcrossprod_parallel(A, B));
    return rcpp_result_gen;
END_RCPP
}
// crossprod_parallel
Rcpp::NumericMatrix crossprod_parallel(Rcpp::NumericMatrix A, Rcpp::NumericMatrix B);
RcppExport SEXP _SGCB_crossprod_parallel(SEXP ASEXP, SEXP BSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type A(ASEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type B(BSEXP);
    rcpp_result_gen = Rcpp::wrap(crossprod_parallel(A, B));
    return rcpp_result_gen;
END_RCPP
}
// rowMeans_parallel
Rcpp::NumericVector rowMeans_parallel(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_rowMeans_parallel(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rowMeans_parallel(X));
    return rcpp_result_gen;
END_RCPP
}
// rowVars_parallel
Rcpp::NumericVector rowVars_parallel(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_rowVars_parallel(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rowVars_parallel(X));
    return rcpp_result_gen;
END_RCPP
}
// rowSums_parallel
Rcpp::NumericVector rowSums_parallel(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_rowSums_parallel(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rowSums_parallel(X));
    return rcpp_result_gen;
END_RCPP
}
// colSums_parallel
Rcpp::NumericVector colSums_parallel(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_colSums_parallel(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(colSums_parallel(X));
    return rcpp_result_gen;
END_RCPP
}
// rowMedians_parallel
Rcpp::NumericVector rowMedians_parallel(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_rowMedians_parallel(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rowMedians_parallel(X));
    return rcpp_result_gen;
END_RCPP
}
// rowQuantiles_parallel
Rcpp::NumericMatrix rowQuantiles_parallel(Rcpp::NumericMatrix X, Rcpp::NumericVector probs);
RcppExport SEXP _SGCB_rowQuantiles_parallel(SEXP XSEXP, SEXP probsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type probs(probsSEXP);
    rcpp_result_gen = Rcpp::wrap(rowQuantiles_parallel(X, probs));
    return rcpp_result_gen;
END_RCPP
}
// log2_transform
Rcpp::NumericMatrix log2_transform(Rcpp::NumericMatrix X, double pseudo);
RcppExport SEXP _SGCB_log2_transform(SEXP XSEXP, SEXP pseudoSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type pseudo(pseudoSEXP);
    rcpp_result_gen = Rcpp::wrap(log2_transform(X, pseudo));
    return rcpp_result_gen;
END_RCPP
}
// zscore_rows
Rcpp::NumericMatrix zscore_rows(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_zscore_rows(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(zscore_rows(X));
    return rcpp_result_gen;
END_RCPP
}
// sweep_rows
Rcpp::NumericMatrix sweep_rows(Rcpp::NumericMatrix X, Rcpp::NumericVector stats, int op);
RcppExport SEXP _SGCB_sweep_rows(SEXP XSEXP, SEXP statsSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_rows(X, stats, op));
    return rcpp_result_gen;
END_RCPP
}
// sweep_cols
Rcpp::NumericMatrix sweep_cols(Rcpp::NumericMatrix X, Rcpp::NumericVector stats, int op);
RcppExport SEXP _SGCB_sweep_cols(SEXP XSEXP, SEXP statsSEXP, SEXP opSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type stats(statsSEXP);
    Rcpp::traits::input_parameter< int >::type op(opSEXP);
    rcpp_result_gen = Rcpp::wrap(sweep_cols(X, stats, op));
    return rcpp_result_gen;
END_RCPP
}
// euclidean_dist_rows
Rcpp::NumericMatrix euclidean_dist_rows(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_euclidean_dist_rows(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(euclidean_dist_rows(X));
    return rcpp_result_gen;
END_RCPP
}
// correlation_matrix
Rcpp::NumericMatrix correlation_matrix(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_correlation_matrix(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(correlation_matrix(X));
    return rcpp_result_gen;
END_RCPP
}
// rank_rows
Rcpp::IntegerMatrix rank_rows(Rcpp::NumericMatrix X);
RcppExport SEXP _SGCB_rank_rows(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(rank_rows(X));
    return rcpp_result_gen;
END_RCPP
}
// order_rows
Rcpp::IntegerMatrix order_rows(Rcpp::NumericMatrix X, bool decreasing);
RcppExport SEXP _SGCB_order_rows(SEXP XSEXP, SEXP decreasingSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< bool >::type decreasing(decreasingSEXP);
    rcpp_result_gen = Rcpp::wrap(order_rows(X, decreasing));
    return rcpp_result_gen;
END_RCPP
}
// digamma_vec
Rcpp::NumericVector digamma_vec(Rcpp::NumericVector x);
RcppExport SEXP _SGCB_digamma_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(digamma_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// trigamma_vec
Rcpp::NumericVector trigamma_vec(Rcpp::NumericVector x);
RcppExport SEXP _SGCB_trigamma_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(trigamma_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// lgamma_vec
Rcpp::NumericVector lgamma_vec(Rcpp::NumericVector x);
RcppExport SEXP _SGCB_lgamma_vec(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(lgamma_vec(x));
    return rcpp_result_gen;
END_RCPP
}
// dnbinom_vec
Rcpp::NumericVector dnbinom_vec(Rcpp::NumericVector x, Rcpp::NumericVector size, Rcpp::NumericVector mu, bool log_p);
RcppExport SEXP _SGCB_dnbinom_vec(SEXP xSEXP, SEXP sizeSEXP, SEXP muSEXP, SEXP log_pSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    Rcpp::traits::input_parameter< bool >::type log_p(log_pSEXP);
    rcpp_result_gen = Rcpp::wrap(dnbinom_vec(x, size, mu, log_p));
    return rcpp_result_gen;
END_RCPP
}
// rnbinom_mat
Rcpp::NumericMatrix rnbinom_mat(int n_genes, int n_samples, Rcpp::NumericVector size, Rcpp::NumericVector mu);
RcppExport SEXP _SGCB_rnbinom_mat(SEXP n_genesSEXP, SEXP n_samplesSEXP, SEXP sizeSEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n_genes(n_genesSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type size(sizeSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(rnbinom_mat(n_genes, n_samples, size, mu));
    return rcpp_result_gen;
END_RCPP
}
// rolling_mean
Rcpp::NumericVector rolling_mean(Rcpp::NumericVector x, int window);
RcppExport SEXP _SGCB_rolling_mean(SEXP xSEXP, SEXP windowSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type window(windowSEXP);
    rcpp_result_gen = Rcpp::wrap(rolling_mean(x, window));
    return rcpp_result_gen;
END_RCPP
}
// loess_smooth
Rcpp::NumericVector loess_smooth(Rcpp::NumericVector x, Rcpp::NumericVector y, double span);
RcppExport SEXP _SGCB_loess_smooth(SEXP xSEXP, SEXP ySEXP, SEXP spanSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type x(xSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< double >::type span(spanSEXP);
    rcpp_result_gen = Rcpp::wrap(loess_smooth(x, y, span));
    return rcpp_result_gen;
END_RCPP
}
// parametric_bootstrap_cpp
NumericMatrix parametric_bootstrap_cpp(NumericVector alpha, NumericVector beta, NumericVector gamma, int n_samples, int n_boot, int seed);
RcppExport SEXP _SGCB_parametric_bootstrap_cpp(SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_samplesSEXP, SEXP n_bootSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_samples(n_samplesSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(parametric_bootstrap_cpp(alpha, beta, gamma, n_samples, n_boot, seed));
    return rcpp_result_gen;
END_RCPP
}
// smoothed_bootstrap_cpp
NumericMatrix smoothed_bootstrap_cpp(NumericMatrix X, int n_boot, double jitter_scale, int seed);
RcppExport SEXP _SGCB_smoothed_bootstrap_cpp(SEXP XSEXP, SEXP n_bootSEXP, SEXP jitter_scaleSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type jitter_scale(jitter_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(smoothed_bootstrap_cpp(X, n_boot, jitter_scale, seed));
    return rcpp_result_gen;
END_RCPP
}
// adaptive_bootstrap_lfc_cpp
List adaptive_bootstrap_lfc_cpp(NumericMatrix X, IntegerVector group, NumericVector alpha, NumericVector beta, NumericVector gamma, int n_boot, double jitter_scale, int seed);
RcppExport SEXP _SGCB_adaptive_bootstrap_lfc_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP alphaSEXP, SEXP betaSEXP, SEXP gammaSEXP, SEXP n_bootSEXP, SEXP jitter_scaleSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha(alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta(betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type jitter_scale(jitter_scaleSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(adaptive_bootstrap_lfc_cpp(X, group, alpha, beta, gamma, n_boot, jitter_scale, seed));
    return rcpp_result_gen;
END_RCPP
}
// parametric_de_test_cpp
List parametric_de_test_cpp(NumericVector alpha_ctrl, NumericVector beta_ctrl, NumericVector gamma_ctrl, NumericVector alpha_treat, NumericVector beta_treat, NumericVector gamma_treat, int n_ctrl, int n_treat, int n_boot, int seed);
RcppExport SEXP _SGCB_parametric_de_test_cpp(SEXP alpha_ctrlSEXP, SEXP beta_ctrlSEXP, SEXP gamma_ctrlSEXP, SEXP alpha_treatSEXP, SEXP beta_treatSEXP, SEXP gamma_treatSEXP, SEXP n_ctrlSEXP, SEXP n_treatSEXP, SEXP n_bootSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type alpha_ctrl(alpha_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_ctrl(beta_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_ctrl(gamma_ctrlSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type alpha_treat(alpha_treatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type beta_treat(beta_treatSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gamma_treat(gamma_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_ctrl(n_ctrlSEXP);
    Rcpp::traits::input_parameter< int >::type n_treat(n_treatSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(parametric_de_test_cpp(alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, n_boot, seed));
    return rcpp_result_gen;
END_RCPP
}
// row_means_cpp
NumericVector row_means_cpp(NumericMatrix X);
RcppExport SEXP _SGCB_row_means_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(row_means_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// row_vars_cpp
NumericVector row_vars_cpp(NumericMatrix X);
RcppExport SEXP _SGCB_row_vars_cpp(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(row_vars_cpp(X));
    return rcpp_result_gen;
END_RCPP
}
// permutation_t_stats_cpp
NumericMatrix permutation_t_stats_cpp(NumericMatrix X, IntegerVector group, int n_perm, int seed);
RcppExport SEXP _SGCB_permutation_t_stats_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_permSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_t_stats_cpp(X, group, n_perm, seed));
    return rcpp_result_gen;
END_RCPP
}
// permutation_pvalues_cpp
NumericVector permutation_pvalues_cpp(NumericMatrix T_all);
RcppExport SEXP _SGCB_permutation_pvalues_cpp(SEXP T_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type T_all(T_allSEXP);
    rcpp_result_gen = Rcpp::wrap(permutation_pvalues_cpp(T_all));
    return rcpp_result_gen;
END_RCPP
}
// dropout_permutation_cpp
NumericMatrix dropout_permutation_cpp(NumericMatrix X, IntegerVector group, int n_perm, int n_dropout, double dropout_rate, int seed);
RcppExport SEXP _SGCB_dropout_permutation_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_permSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_perm(n_permSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(dropout_permutation_cpp(X, group, n_perm, n_dropout, dropout_rate, seed));
    return rcpp_result_gen;
END_RCPP
}
// dropout_pvalues_cpp
NumericVector dropout_pvalues_cpp(NumericMatrix T_all, int n_dropout, double dropout_rate);
RcppExport SEXP _SGCB_dropout_pvalues_cpp(SEXP T_allSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type T_all(T_allSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    rcpp_result_gen = Rcpp::wrap(dropout_pvalues_cpp(T_all, n_dropout, dropout_rate));
    return rcpp_result_gen;
END_RCPP
}
// dropout_lfc_cpp
NumericMatrix dropout_lfc_cpp(NumericMatrix X, IntegerVector group, int n_dropout, double dropout_rate, int seed);
RcppExport SEXP _SGCB_dropout_lfc_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(dropout_lfc_cpp(X, group, n_dropout, dropout_rate, seed));
    return rcpp_result_gen;
END_RCPP
}
// lfc_variance_cpp
NumericVector lfc_variance_cpp(NumericMatrix lfc_all);
RcppExport SEXP _SGCB_lfc_variance_cpp(SEXP lfc_allSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type lfc_all(lfc_allSEXP);
    rcpp_result_gen = Rcpp::wrap(lfc_variance_cpp(lfc_all));
    return rcpp_result_gen;
END_RCPP
}
// log2fc_cpp
NumericVector log2fc_cpp(NumericMatrix X, IntegerVector group, double eps);
RcppExport SEXP _SGCB_log2fc_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(log2fc_cpp(X, group, eps));
    return rcpp_result_gen;
END_RCPP
}
// shrink_variance_cpp
NumericVector shrink_variance_cpp(NumericVector vars, double prior_df, double shrinkage);
RcppExport SEXP _SGCB_shrink_variance_cpp(SEXP varsSEXP, SEXP prior_dfSEXP, SEXP shrinkageSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type vars(varsSEXP);
    Rcpp::traits::input_parameter< double >::type prior_df(prior_dfSEXP);
    Rcpp::traits::input_parameter< double >::type shrinkage(shrinkageSEXP);
    rcpp_result_gen = Rcpp::wrap(shrink_variance_cpp(vars, prior_df, shrinkage));
    return rcpp_result_gen;
END_RCPP
}
// fit_gg_adam_cpp
List fit_gg_adam_cpp(NumericMatrix X, int n_iter, double lr, double weight_decay, double eps);
RcppExport SEXP _SGCB_fit_gg_adam_cpp(SEXP XSEXP, SEXP n_iterSEXP, SEXP lrSEXP, SEXP weight_decaySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type weight_decay(weight_decaySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_gg_adam_cpp(X, n_iter, lr, weight_decay, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_adaptive_pvalue_cpp
List sgcb_adaptive_pvalue_cpp(NumericMatrix X, IntegerVector group, NumericVector ae_alpha, NumericVector ae_beta, NumericVector ae_gamma, NumericVector lfc_stable, NumericVector lfc_var, NumericVector stability, double eps);
RcppExport SEXP _SGCB_sgcb_adaptive_pvalue_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP ae_alphaSEXP, SEXP ae_betaSEXP, SEXP ae_gammaSEXP, SEXP lfc_stableSEXP, SEXP lfc_varSEXP, SEXP stabilitySEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_alpha(ae_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_beta(ae_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_gamma(ae_gammaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lfc_stable(lfc_stableSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type lfc_var(lfc_varSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type stability(stabilitySEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_adaptive_pvalue_cpp(X, group, ae_alpha, ae_beta, ae_gamma, lfc_stable, lfc_var, stability, eps));
    return rcpp_result_gen;
END_RCPP
}
// fast_calibrated_pvalue_cpp
List fast_calibrated_pvalue_cpp(NumericVector T_obs, NumericVector ae_alpha, NumericVector ae_beta, NumericVector ae_gamma, int n_control, int n_boot, double eps);
RcppExport SEXP _SGCB_fast_calibrated_pvalue_cpp(SEXP T_obsSEXP, SEXP ae_alphaSEXP, SEXP ae_betaSEXP, SEXP ae_gammaSEXP, SEXP n_controlSEXP, SEXP n_bootSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type T_obs(T_obsSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_alpha(ae_alphaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_beta(ae_betaSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type ae_gamma(ae_gammaSEXP);
    Rcpp::traits::input_parameter< int >::type n_control(n_controlSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fast_calibrated_pvalue_cpp(T_obs, ae_alpha, ae_beta, ae_gamma, n_control, n_boot, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_fast_inference_cpp
List sgcb_fast_inference_cpp(NumericMatrix X, IntegerVector group, int n_dropout, double dropout_rate, int seed, double eps);
RcppExport SEXP _SGCB_sgcb_fast_inference_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP seedSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_fast_inference_cpp(X, group, n_dropout, dropout_rate, seed, eps));
    return rcpp_result_gen;
END_RCPP
}
// fit_wide_shallow_ae_cpp
List fit_wide_shallow_ae_cpp(NumericMatrix X, int n_iter, int h_ratio, double lr, double eps);
RcppExport SEXP _SGCB_fit_wide_shallow_ae_cpp(SEXP XSEXP, SEXP n_iterSEXP, SEXP h_ratioSEXP, SEXP lrSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type n_iter(n_iterSEXP);
    Rcpp::traits::input_parameter< int >::type h_ratio(h_ratioSEXP);
    Rcpp::traits::input_parameter< double >::type lr(lrSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(fit_wide_shallow_ae_cpp(X, n_iter, h_ratio, lr, eps));
    return rcpp_result_gen;
END_RCPP
}
// sde_dropout_stability_cpp
List sde_dropout_stability_cpp(NumericMatrix X, IntegerVector group, int n_dropout, double dropout_rate, int seed);
RcppExport SEXP _SGCB_sde_dropout_stability_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sde_dropout_stability_cpp(X, group, n_dropout, dropout_rate, seed));
    return rcpp_result_gen;
END_RCPP
}
// squeeze_var_cpp
List squeeze_var_cpp(NumericVector var, int df, double eps);
RcppExport SEXP _SGCB_squeeze_var_cpp(SEXP varSEXP, SEXP dfSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type var(varSEXP);
    Rcpp::traits::input_parameter< int >::type df(dfSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    rcpp_result_gen = Rcpp::wrap(squeeze_var_cpp(var, df, eps));
    return rcpp_result_gen;
END_RCPP
}
// sgcb_inference_cpp
List sgcb_inference_cpp(NumericMatrix X, IntegerVector group, int n_boot, int n_dropout, double dropout_rate, int ae_iter, double ae_lr, int seed);
RcppExport SEXP _SGCB_sgcb_inference_cpp(SEXP XSEXP, SEXP groupSEXP, SEXP n_bootSEXP, SEXP n_dropoutSEXP, SEXP dropout_rateSEXP, SEXP ae_iterSEXP, SEXP ae_lrSEXP, SEXP seedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type group(groupSEXP);
    Rcpp::traits::input_parameter< int >::type n_boot(n_bootSEXP);
    Rcpp::traits::input_parameter< int >::type n_dropout(n_dropoutSEXP);
    Rcpp::traits::input_parameter< double >::type dropout_rate(dropout_rateSEXP);
    Rcpp::traits::input_parameter< int >::type ae_iter(ae_iterSEXP);
    Rcpp::traits::input_parameter< double >::type ae_lr(ae_lrSEXP);
    Rcpp::traits::input_parameter< int >::type seed(seedSEXP);
    rcpp_result_gen = Rcpp::wrap(sgcb_inference_cpp(X, group, n_boot, n_dropout, dropout_rate, ae_iter, ae_lr, seed));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_SGCB_adaptive_squeeze_var_cpp", (DL_FUNC) &_SGCB_adaptive_squeeze_var_cpp, 4},
    {"_SGCB_adaptive_moderated_t_cpp", (DL_FUNC) &_SGCB_adaptive_moderated_t_cpp, 7},
    {"_SGCB_sgcb_adaptive_inference_cpp", (DL_FUNC) &_SGCB_sgcb_adaptive_inference_cpp, 9},
    {"_SGCB_resample_indices", (DL_FUNC) &_SGCB_resample_indices, 4},
    {"_SGCB_bootstrap_resample", (DL_FUNC) &_SGCB_bootstrap_resample, 2},
    {"_SGCB_bootstrap_mean", (DL_FUNC) &_SGCB_bootstrap_mean, 3},
    {"_SGCB_bootstrap_gene_stats", (DL_FUNC) &_SGCB_bootstrap_gene_stats, 8},
    {"_SGCB_calibrated_bootstrap_search", (DL_FUNC) &_SGCB_calibrated_bootstrap_search, 10},
    {"_SGCB_permutation_pvalues", (DL_FUNC) &_SGCB_permutation_pvalues, 2},
    {"_SGCB_bootstrap_confidence_intervals", (DL_FUNC) &_SGCB_bootstrap_confidence_intervals, 2},
    {"_SGCB_bh_adjust", (DL_FUNC) &_SGCB_bh_adjust, 1},
    {"_SGCB_bonferroni_adjust", (DL_FUNC) &_SGCB_bonferroni_adjust, 1},
    {"_SGCB_holm_adjust", (DL_FUNC) &_SGCB_holm_adjust, 1},
    {"_SGCB_effect_sizes", (DL_FUNC) &_SGCB_effect_sizes, 3},
    {"_SGCB_shrink_lfc_normal", (DL_FUNC) &_SGCB_shrink_lfc_normal, 3},
    {"_SGCB_shrink_lfc_cauchy", (DL_FUNC) &_SGCB_shrink_lfc_cauchy, 3},
    {"_SGCB_calibrated_bootstrap_gene_cpp", (DL_FUNC) &_SGCB_calibrated_bootstrap_gene_cpp, 5},
    {"_SGCB_calibrated_bootstrap_all_cpp", (DL_FUNC) &_SGCB_calibrated_bootstrap_all_cpp, 5},
    {"_SGCB_gg_mle_single_cpp", (DL_FUNC) &_SGCB_gg_mle_single_cpp, 3},
    {"_SGCB_gg_mle_all_cpp", (DL_FUNC) &_SGCB_gg_mle_all_cpp, 3},
    {"_SGCB_fit_conditional_ae_cpp", (DL_FUNC) &_SGCB_fit_conditional_ae_cpp, 7},
    {"_SGCB_conditional_de_test_cpp", (DL_FUNC) &_SGCB_conditional_de_test_cpp, 11},
    {"_SGCB_remove_batch_effect_cpp", (DL_FUNC) &_SGCB_remove_batch_effect_cpp, 3},
    {"_SGCB_local_weighted_regression_cpp", (DL_FUNC) &_SGCB_local_weighted_regression_cpp, 4},
    {"_SGCB_column_medians_cpp", (DL_FUNC) &_SGCB_column_medians_cpp, 2},
    {"_SGCB_row_medians_cpp", (DL_FUNC) &_SGCB_row_medians_cpp, 2},
    {"_SGCB_tmm_factors_cpp", (DL_FUNC) &_SGCB_tmm_factors_cpp, 6},
    {"_SGCB_fit_dispersion_trend_parametric_cpp", (DL_FUNC) &_SGCB_fit_dispersion_trend_parametric_cpp, 3},
    {"_SGCB_estimate_disp_tagwise_cpp", (DL_FUNC) &_SGCB_estimate_disp_tagwise_cpp, 5},
    {"_SGCB_row_quantiles_cpp", (DL_FUNC) &_SGCB_row_quantiles_cpp, 3},
    {"_SGCB_gg_loglik_vec", (DL_FUNC) &_SGCB_gg_loglik_vec, 5},
    {"_SGCB_gg_grad_params", (DL_FUNC) &_SGCB_gg_grad_params, 5},
    {"_SGCB_gg_hessian_diag", (DL_FUNC) &_SGCB_gg_hessian_diag, 5},
    {"_SGCB_gg_sample_mat", (DL_FUNC) &_SGCB_gg_sample_mat, 6},
    {"_SGCB_clip_value", (DL_FUNC) &_SGCB_clip_value, 3},
    {"_SGCB_clip_vec", (DL_FUNC) &_SGCB_clip_vec, 3},
    {"_SGCB_adam_update", (DL_FUNC) &_SGCB_adam_update, 9},
    {"_SGCB_softplus_mat", (DL_FUNC) &_SGCB_softplus_mat, 2},
    {"_SGCB_softplus_grad_mat", (DL_FUNC) &_SGCB_softplus_grad_mat, 2},
    {"_SGCB_clip_mat", (DL_FUNC) &_SGCB_clip_mat, 3},
    {"_SGCB_fisher_info_diag", (DL_FUNC) &_SGCB_fisher_info_diag, 4},
    {"_SGCB_compute_lfc", (DL_FUNC) &_SGCB_compute_lfc, 7},
    {"_SGCB_compute_T_stat_batch", (DL_FUNC) &_SGCB_compute_T_stat_batch, 9},
    {"_SGCB_compute_coverage_error", (DL_FUNC) &_SGCB_compute_coverage_error, 3},
    {"_SGCB_compute_empirical_pvalues", (DL_FUNC) &_SGCB_compute_empirical_pvalues, 2},
    {"_SGCB_fit_gg_natural_gradient_cpp", (DL_FUNC) &_SGCB_fit_gg_natural_gradient_cpp, 6},
    {"_SGCB_fit_gg_hierarchical_bayes_cpp", (DL_FUNC) &_SGCB_fit_gg_hierarchical_bayes_cpp, 6},
    {"_SGCB_adaptive_squeeze_var_gg_informed_cpp", (DL_FUNC) &_SGCB_adaptive_squeeze_var_gg_informed_cpp, 6},
    {"_SGCB_adaptive_squeeze_var_hierarchical_cpp", (DL_FUNC) &_SGCB_adaptive_squeeze_var_hierarchical_cpp, 4},
    {"_SGCB_manifold_distance_test_cpp", (DL_FUNC) &_SGCB_manifold_distance_test_cpp, 9},
    {"_SGCB_sgcb_wls_ebayes_cpp", (DL_FUNC) &_SGCB_sgcb_wls_ebayes_cpp, 6},
    {"_SGCB_sgcb_info_geom_inference_cpp", (DL_FUNC) &_SGCB_sgcb_info_geom_inference_cpp, 7},
    {"_SGCB_matmul_parallel", (DL_FUNC) &_SGCB_matmul_parallel, 2},
    {"_SGCB_tcrossprod_parallel", (DL_FUNC) &_SGCB_tcrossprod_parallel, 2},
    {"_SGCB_crossprod_parallel", (DL_FUNC) &_SGCB_crossprod_parallel, 2},
    {"_SGCB_rowMeans_parallel", (DL_FUNC) &_SGCB_rowMeans_parallel, 1},
    {"_SGCB_rowVars_parallel", (DL_FUNC) &_SGCB_rowVars_parallel, 1},
    {"_SGCB_rowSums_parallel", (DL_FUNC) &_SGCB_rowSums_parallel, 1},
    {"_SGCB_colSums_parallel", (DL_FUNC) &_SGCB_colSums_parallel, 1},
    {"_SGCB_rowMedians_parallel", (DL_FUNC) &_SGCB_rowMedians_parallel, 1},
    {"_SGCB_rowQuantiles_parallel", (DL_FUNC) &_SGCB_rowQuantiles_parallel, 2},
    {"_SGCB_log2_transform", (DL_FUNC) &_SGCB_log2_transform, 2},
    {"_SGCB_zscore_rows", (DL_FUNC) &_SGCB_zscore_rows, 1},
    {"_SGCB_sweep_rows", (DL_FUNC) &_SGCB_sweep_rows, 3},
    {"_SGCB_sweep_cols", (DL_FUNC) &_SGCB_sweep_cols, 3},
    {"_SGCB_euclidean_dist_rows", (DL_FUNC) &_SGCB_euclidean_dist_rows, 1},
    {"_SGCB_correlation_matrix", (DL_FUNC) &_SGCB_correlation_matrix, 1},
    {"_SGCB_rank_rows", (DL_FUNC) &_SGCB_rank_rows, 1},
    {"_SGCB_order_rows", (DL_FUNC) &_SGCB_order_rows, 2},
    {"_SGCB_digamma_vec", (DL_FUNC) &_SGCB_digamma_vec, 1},
    {"_SGCB_trigamma_vec", (DL_FUNC) &_SGCB_trigamma_vec, 1},
    {"_SGCB_lgamma_vec", (DL_FUNC) &_SGCB_lgamma_vec, 1},
    {"_SGCB_dnbinom_vec", (DL_FUNC) &_SGCB_dnbinom_vec, 4},
    {"_SGCB_rnbinom_mat", (DL_FUNC) &_SGCB_rnbinom_mat, 4},
    {"_SGCB_rolling_mean", (DL_FUNC) &_SGCB_rolling_mean, 2},
    {"_SGCB_loess_smooth", (DL_FUNC) &_SGCB_loess_smooth, 3},
    {"_SGCB_parametric_bootstrap_cpp", (DL_FUNC) &_SGCB_parametric_bootstrap_cpp, 6},
    {"_SGCB_smoothed_bootstrap_cpp", (DL_FUNC) &_SGCB_smoothed_bootstrap_cpp, 4},
    {"_SGCB_adaptive_bootstrap_lfc_cpp", (DL_FUNC) &_SGCB_adaptive_bootstrap_lfc_cpp, 8},
    {"_SGCB_parametric_de_test_cpp", (DL_FUNC) &_SGCB_parametric_de_test_cpp, 10},
    {"_SGCB_row_means_cpp", (DL_FUNC) &_SGCB_row_means_cpp, 1},
    {"_SGCB_row_vars_cpp", (DL_FUNC) &_SGCB_row_vars_cpp, 1},
    {"_SGCB_permutation_t_stats_cpp", (DL_FUNC) &_SGCB_permutation_t_stats_cpp, 4},
    {"_SGCB_permutation_pvalues_cpp", (DL_FUNC) &_SGCB_permutation_pvalues_cpp, 1},
    {"_SGCB_dropout_permutation_cpp", (DL_FUNC) &_SGCB_dropout_permutation_cpp, 6},
    {"_SGCB_dropout_pvalues_cpp", (DL_FUNC) &_SGCB_dropout_pvalues_cpp, 3},
    {"_SGCB_dropout_lfc_cpp", (DL_FUNC) &_SGCB_dropout_lfc_cpp, 5},
    {"_SGCB_lfc_variance_cpp", (DL_FUNC) &_SGCB_lfc_variance_cpp, 1},
    {"_SGCB_log2fc_cpp", (DL_FUNC) &_SGCB_log2fc_cpp, 3},
    {"_SGCB_shrink_variance_cpp", (DL_FUNC) &_SGCB_shrink_variance_cpp, 3},
    {"_SGCB_fit_gg_adam_cpp", (DL_FUNC) &_SGCB_fit_gg_adam_cpp, 5},
    {"_SGCB_sgcb_adaptive_pvalue_cpp", (DL_FUNC) &_SGCB_sgcb_adaptive_pvalue_cpp, 9},
    {"_SGCB_fast_calibrated_pvalue_cpp", (DL_FUNC) &_SGCB_fast_calibrated_pvalue_cpp, 7},
    {"_SGCB_sgcb_fast_inference_cpp", (DL_FUNC) &_SGCB_sgcb_fast_inference_cpp, 6},
    {"_SGCB_fit_wide_shallow_ae_cpp", (DL_FUNC) &_SGCB_fit_wide_shallow_ae_cpp, 5},
    {"_SGCB_sde_dropout_stability_cpp", (DL_FUNC) &_SGCB_sde_dropout_stability_cpp, 5},
    {"_SGCB_squeeze_var_cpp", (DL_FUNC) &_SGCB_squeeze_var_cpp, 3},
    {"_SGCB_sgcb_inference_cpp", (DL_FUNC) &_SGCB_sgcb_inference_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_SGCB(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
