# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

adaptive_squeeze_var_cpp <- function(var, df, n_samples, eps = 1e-15) {
    .Call(`_SGCB_adaptive_squeeze_var_cpp`, var, df, n_samples, eps)
}

adaptive_moderated_t_cpp <- function(X, group, ae_alpha, ae_beta, ae_gamma, stability, eps = 1e-8) {
    .Call(`_SGCB_adaptive_moderated_t_cpp`, X, group, ae_alpha, ae_beta, ae_gamma, stability, eps)
}

sgcb_adaptive_inference_cpp <- function(X, group, ae_alpha, ae_beta, ae_gamma, lfc_stable, lfc_var, stability, eps = 1e-8) {
    .Call(`_SGCB_sgcb_adaptive_inference_cpp`, X, group, ae_alpha, ae_beta, ae_gamma, lfc_stable, lfc_var, stability, eps)
}

resample_indices <- function(n, m, B, seed = 12345L) {
    .Call(`_SGCB_resample_indices`, n, m, B, seed)
}

bootstrap_resample <- function(X, indices) {
    .Call(`_SGCB_bootstrap_resample`, X, indices)
}

bootstrap_mean <- function(X, B, seed = 12345L) {
    .Call(`_SGCB_bootstrap_mean`, X, B, seed)
}

bootstrap_gene_stats <- function(X, alpha, beta, gamma, m, B, eps = 1e-8, seed = 12345L) {
    .Call(`_SGCB_bootstrap_gene_stats`, X, alpha, beta, gamma, m, B, eps, seed)
}

calibrated_bootstrap_search <- function(X, alpha, beta, gamma, T_obs, m_fracs, cb_reps, target_coverage = 0.5, eps = 1e-8, seed = 12345L) {
    .Call(`_SGCB_calibrated_bootstrap_search`, X, alpha, beta, gamma, T_obs, m_fracs, cb_reps, target_coverage, eps, seed)
}

permutation_pvalues <- function(T_obs, T_null) {
    .Call(`_SGCB_permutation_pvalues`, T_obs, T_null)
}

bootstrap_confidence_intervals <- function(T_null, alpha = 0.05) {
    .Call(`_SGCB_bootstrap_confidence_intervals`, T_null, alpha)
}

bh_adjust <- function(pvals) {
    .Call(`_SGCB_bh_adjust`, pvals)
}

bonferroni_adjust <- function(pvals) {
    .Call(`_SGCB_bonferroni_adjust`, pvals)
}

holm_adjust <- function(pvals) {
    .Call(`_SGCB_holm_adjust`, pvals)
}

effect_sizes <- function(control, treat, eps = 1e-8) {
    .Call(`_SGCB_effect_sizes`, control, treat, eps)
}

shrink_lfc_normal <- function(lfc, lfc_se, prior_scale = 1.0) {
    .Call(`_SGCB_shrink_lfc_normal`, lfc, lfc_se, prior_scale)
}

shrink_lfc_cauchy <- function(lfc, lfc_se, prior_scale = 1.0) {
    .Call(`_SGCB_shrink_lfc_cauchy`, lfc, lfc_se, prior_scale)
}

calibrated_bootstrap_gene_cpp <- function(x_ctrl, x_treat, n_boot = 200L, m_ratio = 0.7, seed = 12345L) {
    .Call(`_SGCB_calibrated_bootstrap_gene_cpp`, x_ctrl, x_treat, n_boot, m_ratio, seed)
}

calibrated_bootstrap_all_cpp <- function(X, group, n_boot = 200L, m_ratio = 0.7, seed = 12345L) {
    .Call(`_SGCB_calibrated_bootstrap_all_cpp`, X, group, n_boot, m_ratio, seed)
}

gg_mle_single_cpp <- function(x, max_iter = 50L, tol = 1e-6) {
    .Call(`_SGCB_gg_mle_single_cpp`, x, max_iter, tol)
}

gg_mle_all_cpp <- function(X, max_iter = 50L, tol = 1e-6) {
    .Call(`_SGCB_gg_mle_all_cpp`, X, max_iter, tol)
}

fit_conditional_ae_cpp <- function(X, batch, condition, n_iter = 100L, h_ratio = 2L, lr = 0.01, eps = 1e-8) {
    .Call(`_SGCB_fit_conditional_ae_cpp`, X, batch, condition, n_iter, h_ratio, lr, eps)
}

conditional_de_test_cpp <- function(X, batch, condition, alpha, beta, gamma, batch_effect, cond_ctrl = 0L, cond_treat = 1L, n_boot = 200L, eps = 1e-8) {
    .Call(`_SGCB_conditional_de_test_cpp`, X, batch, condition, alpha, beta, gamma, batch_effect, cond_ctrl, cond_treat, n_boot, eps)
}

remove_batch_effect_cpp <- function(X, batch, batch_effect) {
    .Call(`_SGCB_remove_batch_effect_cpp`, X, batch, batch_effect)
}

local_weighted_regression_cpp <- function(x, y, span = 0.3, n_threads = 0L) {
    .Call(`_SGCB_local_weighted_regression_cpp`, x, y, span, n_threads)
}

column_medians_cpp <- function(X, n_threads = 0L) {
    .Call(`_SGCB_column_medians_cpp`, X, n_threads)
}

row_medians_cpp <- function(X, n_threads = 0L) {
    .Call(`_SGCB_row_medians_cpp`, X, n_threads)
}

tmm_factors_cpp <- function(counts, ref_idx, trim_m = 0.3, trim_a = 0.05, eps = 1e-8, n_threads = 0L) {
    .Call(`_SGCB_tmm_factors_cpp`, counts, ref_idx, trim_m, trim_a, eps, n_threads)
}

fit_dispersion_trend_parametric_cpp <- function(means, dispersions, eps = 1e-8) {
    .Call(`_SGCB_fit_dispersion_trend_parametric_cpp`, means, dispersions, eps)
}

estimate_disp_tagwise_cpp <- function(counts, span = 0.3, prior_df = 10.0, eps = 1e-8, n_threads = 0L) {
    .Call(`_SGCB_estimate_disp_tagwise_cpp`, counts, span, prior_df, eps, n_threads)
}

row_quantiles_cpp <- function(X, probs, n_threads = 0L) {
    .Call(`_SGCB_row_quantiles_cpp`, X, probs, n_threads)
}

gg_loglik_vec <- function(x, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_loglik_vec`, x, alpha, beta, gamma, eps)
}

gg_grad_params <- function(x, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_grad_params`, x, alpha, beta, gamma, eps)
}

gg_hessian_diag <- function(x, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_hessian_diag`, x, alpha, beta, gamma, eps)
}

gg_sample_mat <- function(n_genes, n_samples, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_sample_mat`, n_genes, n_samples, alpha, beta, gamma, eps)
}

clip_value <- function(x, lo, hi) {
    .Call(`_SGCB_clip_value`, x, lo, hi)
}

clip_vec <- function(x, lo, hi) {
    .Call(`_SGCB_clip_vec`, x, lo, hi)
}

adam_update <- function(param, grad, m, v, lr, beta1, beta2, eps, t) {
    .Call(`_SGCB_adam_update`, param, grad, m, v, lr, beta1, beta2, eps, t)
}

softplus_mat <- function(x, threshold = 20.0) {
    .Call(`_SGCB_softplus_mat`, x, threshold)
}

softplus_grad_mat <- function(x, threshold = 20.0) {
    .Call(`_SGCB_softplus_grad_mat`, x, threshold)
}

clip_mat <- function(x, lo, hi) {
    .Call(`_SGCB_clip_mat`, x, lo, hi)
}

fisher_info_diag <- function(alpha, beta, gamma, n_samples) {
    .Call(`_SGCB_fisher_info_diag`, alpha, beta, gamma, n_samples)
}

compute_lfc <- function(treat_mean, control_mean, treat_var, control_var, n_treat, n_control, eps = 1e-8) {
    .Call(`_SGCB_compute_lfc`, treat_mean, control_mean, treat_var, control_var, n_treat, n_control, eps)
}

compute_T_stat_batch <- function(X, alpha, beta, gamma, n_genes, n_samples, n_batches, batch_size, eps = 1e-8) {
    .Call(`_SGCB_compute_T_stat_batch`, X, alpha, beta, gamma, n_genes, n_samples, n_batches, batch_size, eps)
}

compute_coverage_error <- function(T_null_mat, T_obs, target_coverage = 0.5) {
    .Call(`_SGCB_compute_coverage_error`, T_null_mat, T_obs, target_coverage)
}

compute_empirical_pvalues <- function(T_null_mat, T_obs) {
    .Call(`_SGCB_compute_empirical_pvalues`, T_null_mat, T_obs)
}

fit_gg_natural_gradient_cpp <- function(X, n_iter = -1L, lr = -1, weight_decay = -1, use_natural_grad = TRUE, use_firth_override = TRUE, use_gamma_submodel = TRUE, eps = 1e-8) {
    .Call(`_SGCB_fit_gg_natural_gradient_cpp`, X, n_iter, lr, weight_decay, use_natural_grad, use_firth_override, use_gamma_submodel, eps)
}

fit_gg_hierarchical_bayes_cpp <- function(X, n_iter = -1L, lr = -1, prior_strength = -1, use_natural_grad = TRUE, eps = 1e-8) {
    .Call(`_SGCB_fit_gg_hierarchical_bayes_cpp`, X, n_iter, lr, prior_strength, use_natural_grad, eps)
}

adaptive_squeeze_var_gg_informed_cpp <- function(vars, gg_alpha, gg_beta, gg_gamma, n_samples, eps = 1e-8) {
    .Call(`_SGCB_adaptive_squeeze_var_gg_informed_cpp`, vars, gg_alpha, gg_beta, gg_gamma, n_samples, eps)
}

adaptive_squeeze_var_hierarchical_cpp <- function(vars, gene_means, n_samples, eps = 1e-8) {
    .Call(`_SGCB_adaptive_squeeze_var_hierarchical_cpp`, vars, gene_means, n_samples, eps)
}

manifold_distance_test_cpp <- function(alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, eps = 1e-8) {
    .Call(`_SGCB_manifold_distance_test_cpp`, alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, eps)
}

sgcb_wls_ebayes_cpp <- function(y, design, contrast, gene_means, weights, eps = 1e-8) {
    .Call(`_SGCB_sgcb_wls_ebayes_cpp`, y, design, contrast, gene_means, weights, eps)
}

sgcb_info_geom_inference_cpp <- function(X, group, n_dropout = 50L, dropout_rate = 0.2, use_natural_grad = TRUE, use_hierarchical = TRUE, use_firth = TRUE, use_gamma_submodel = TRUE, use_gg_variance = TRUE, eps = 1e-8) {
    .Call(`_SGCB_sgcb_info_geom_inference_cpp`, X, group, n_dropout, dropout_rate, use_natural_grad, use_hierarchical, use_firth, use_gamma_submodel, use_gg_variance, eps)
}

matmul_parallel <- function(A, B) {
    .Call(`_SGCB_matmul_parallel`, A, B)
}

tcrossprod_parallel <- function(A, B) {
    .Call(`_SGCB_tcrossprod_parallel`, A, B)
}

crossprod_parallel <- function(A, B) {
    .Call(`_SGCB_crossprod_parallel`, A, B)
}

rowMeans_parallel <- function(X) {
    .Call(`_SGCB_rowMeans_parallel`, X)
}

rowVars_parallel <- function(X) {
    .Call(`_SGCB_rowVars_parallel`, X)
}

rowSums_parallel <- function(X) {
    .Call(`_SGCB_rowSums_parallel`, X)
}

colSums_parallel <- function(X) {
    .Call(`_SGCB_colSums_parallel`, X)
}

rowMedians_parallel <- function(X) {
    .Call(`_SGCB_rowMedians_parallel`, X)
}

rowQuantiles_parallel <- function(X, probs) {
    .Call(`_SGCB_rowQuantiles_parallel`, X, probs)
}

log2_transform <- function(X, pseudo = 1.0) {
    .Call(`_SGCB_log2_transform`, X, pseudo)
}

zscore_rows <- function(X) {
    .Call(`_SGCB_zscore_rows`, X)
}

sweep_rows <- function(X, stats, op = 1L) {
    .Call(`_SGCB_sweep_rows`, X, stats, op)
}

sweep_cols <- function(X, stats, op = 1L) {
    .Call(`_SGCB_sweep_cols`, X, stats, op)
}

euclidean_dist_rows <- function(X) {
    .Call(`_SGCB_euclidean_dist_rows`, X)
}

correlation_matrix <- function(X) {
    .Call(`_SGCB_correlation_matrix`, X)
}

rank_rows <- function(X) {
    .Call(`_SGCB_rank_rows`, X)
}

order_rows <- function(X, decreasing = FALSE) {
    .Call(`_SGCB_order_rows`, X, decreasing)
}

digamma_vec <- function(x) {
    .Call(`_SGCB_digamma_vec`, x)
}

trigamma_vec <- function(x) {
    .Call(`_SGCB_trigamma_vec`, x)
}

lgamma_vec <- function(x) {
    .Call(`_SGCB_lgamma_vec`, x)
}

dnbinom_vec <- function(x, size, mu, log_p = FALSE) {
    .Call(`_SGCB_dnbinom_vec`, x, size, mu, log_p)
}

rnbinom_mat <- function(n_genes, n_samples, size, mu) {
    .Call(`_SGCB_rnbinom_mat`, n_genes, n_samples, size, mu)
}

rolling_mean <- function(x, window) {
    .Call(`_SGCB_rolling_mean`, x, window)
}

loess_smooth <- function(x, y, span = 0.3) {
    .Call(`_SGCB_loess_smooth`, x, y, span)
}

parametric_bootstrap_cpp <- function(alpha, beta, gamma, n_samples, n_boot, seed = 12345L) {
    .Call(`_SGCB_parametric_bootstrap_cpp`, alpha, beta, gamma, n_samples, n_boot, seed)
}

smoothed_bootstrap_cpp <- function(X, n_boot, jitter_scale = 0.1, seed = 12345L) {
    .Call(`_SGCB_smoothed_bootstrap_cpp`, X, n_boot, jitter_scale, seed)
}

adaptive_bootstrap_lfc_cpp <- function(X, group, alpha, beta, gamma, n_boot = 200L, jitter_scale = 0.1, seed = 12345L) {
    .Call(`_SGCB_adaptive_bootstrap_lfc_cpp`, X, group, alpha, beta, gamma, n_boot, jitter_scale, seed)
}

parametric_de_test_cpp <- function(alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, n_boot = 500L, seed = 12345L) {
    .Call(`_SGCB_parametric_de_test_cpp`, alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, n_boot, seed)
}

row_means_cpp <- function(X) {
    .Call(`_SGCB_row_means_cpp`, X)
}

row_vars_cpp <- function(X) {
    .Call(`_SGCB_row_vars_cpp`, X)
}

permutation_t_stats_cpp <- function(X, group, n_perm, seed = 12345L) {
    .Call(`_SGCB_permutation_t_stats_cpp`, X, group, n_perm, seed)
}

permutation_pvalues_cpp <- function(T_all) {
    .Call(`_SGCB_permutation_pvalues_cpp`, T_all)
}

dropout_permutation_cpp <- function(X, group, n_perm, n_dropout, dropout_rate, seed = 12345L) {
    .Call(`_SGCB_dropout_permutation_cpp`, X, group, n_perm, n_dropout, dropout_rate, seed)
}

dropout_pvalues_cpp <- function(T_all, n_dropout, dropout_rate) {
    .Call(`_SGCB_dropout_pvalues_cpp`, T_all, n_dropout, dropout_rate)
}

dropout_lfc_cpp <- function(X, group, n_dropout, dropout_rate, seed = 12345L) {
    .Call(`_SGCB_dropout_lfc_cpp`, X, group, n_dropout, dropout_rate, seed)
}

lfc_variance_cpp <- function(lfc_all) {
    .Call(`_SGCB_lfc_variance_cpp`, lfc_all)
}

log2fc_cpp <- function(X, group, eps = 1e-8) {
    .Call(`_SGCB_log2fc_cpp`, X, group, eps)
}

shrink_variance_cpp <- function(vars, prior_df = 3.0, shrinkage = 0.5) {
    .Call(`_SGCB_shrink_variance_cpp`, vars, prior_df, shrinkage)
}

fit_gg_adam_cpp <- function(X, n_iter = -1L, lr = -1, weight_decay = -1, eps = 1e-8) {
    .Call(`_SGCB_fit_gg_adam_cpp`, X, n_iter, lr, weight_decay, eps)
}

sgcb_adaptive_pvalue_cpp <- function(X, group, ae_alpha, ae_beta, ae_gamma, lfc_stable, lfc_var, stability, eps = 1e-8) {
    .Call(`_SGCB_sgcb_adaptive_pvalue_cpp`, X, group, ae_alpha, ae_beta, ae_gamma, lfc_stable, lfc_var, stability, eps)
}

fast_calibrated_pvalue_cpp <- function(T_obs, ae_alpha, ae_beta, ae_gamma, n_control, n_boot = 100L, eps = 1e-8) {
    .Call(`_SGCB_fast_calibrated_pvalue_cpp`, T_obs, ae_alpha, ae_beta, ae_gamma, n_control, n_boot, eps)
}

sgcb_fast_inference_cpp <- function(X, group, n_dropout = 50L, dropout_rate = 0.2, seed = 12345L, eps = 1e-8) {
    .Call(`_SGCB_sgcb_fast_inference_cpp`, X, group, n_dropout, dropout_rate, seed, eps)
}

fit_wide_shallow_ae_cpp <- function(X, n_iter = 100L, h_ratio = 2L, lr = 0.01, eps = 1e-8) {
    .Call(`_SGCB_fit_wide_shallow_ae_cpp`, X, n_iter, h_ratio, lr, eps)
}

sde_dropout_stability_cpp <- function(X, group, n_dropout = 50L, dropout_rate = 0.2, seed = 12345L) {
    .Call(`_SGCB_sde_dropout_stability_cpp`, X, group, n_dropout, dropout_rate, seed)
}

squeeze_var_cpp <- function(var, df, eps = 1e-15) {
    .Call(`_SGCB_squeeze_var_cpp`, var, df, eps)
}

sgcb_inference_cpp <- function(X, group, n_boot = 200L, n_dropout = 50L, dropout_rate = 0.2, ae_iter = 50L, ae_lr = 0.01, seed = 12345L) {
    .Call(`_SGCB_sgcb_inference_cpp`, X, group, n_boot, n_dropout, dropout_rate, ae_iter, ae_lr, seed)
}

