# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

shrink_lfc_normal <- function(lfc, lfc_se, prior_scale = 1.0) {
    .Call(`_SGCB_shrink_lfc_normal`, lfc, lfc_se, prior_scale)
}

shrink_lfc_cauchy <- function(lfc, lfc_se, prior_scale = 1.0) {
    .Call(`_SGCB_shrink_lfc_cauchy`, lfc, lfc_se, prior_scale)
}

tmm_factors_cpp <- function(counts, ref_idx, trim_m = 0.3, trim_a = 0.05, eps = 1e-8, n_threads = 0L) {
    .Call(`_SGCB_tmm_factors_cpp`, counts, ref_idx, trim_m, trim_a, eps, n_threads)
}

row_quantiles_cpp <- function(X, probs, n_threads = 0L) {
    .Call(`_SGCB_row_quantiles_cpp`, X, probs, n_threads)
}

gg_loglik_vec <- function(x, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_loglik_vec`, x, alpha, beta, gamma, eps)
}

gg_grad_params <- function(x, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_grad_params`, x, alpha, beta, gamma, eps)
}

gg_hessian_diag <- function(x, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_hessian_diag`, x, alpha, beta, gamma, eps)
}

gg_sample_mat <- function(n_genes, n_samples, alpha, beta, gamma, eps = 1e-8) {
    .Call(`_SGCB_gg_sample_mat`, n_genes, n_samples, alpha, beta, gamma, eps)
}

fisher_info_diag <- function(alpha, beta, gamma, n_samples) {
    .Call(`_SGCB_fisher_info_diag`, alpha, beta, gamma, n_samples)
}

fisher_info_schur_ag <- function(alpha, beta, gamma, n_samples) {
    .Call(`_SGCB_fisher_info_schur_ag`, alpha, beta, gamma, n_samples)
}

fisher_info_full_inverse <- function(alpha, beta, gamma, n_samples) {
    .Call(`_SGCB_fisher_info_full_inverse`, alpha, beta, gamma, n_samples)
}

sgcb_dreg_v1_cpp <- function(y, design, contrast, max_outer = 20L, max_inner_ag = 40L, ag_lr = 0.15, tol = 1e-5, eps = 1e-8) {
    .Call(`_SGCB_sgcb_dreg_v1_cpp`, y, design, contrast, max_outer, max_inner_ag, ag_lr, tol, eps)
}

sgcb_dreg_dv_cpp <- function(y, design_mean, design_disp, contrast_disp, coef_v1, alpha_v1, gamma_v1, max_outer_dv = 15L, max_inner_d = 8L, d_lr = 0.5, eps = 1e-8) {
    .Call(`_SGCB_sgcb_dreg_dv_cpp`, y, design_mean, design_disp, contrast_disp, coef_v1, alpha_v1, gamma_v1, max_outer_dv, max_inner_d, d_lr, eps)
}

fit_gg_natural_gradient_cpp <- function(X, n_iter = -1L, lr = -1, weight_decay = -1, use_natural_grad = TRUE, use_firth_override = TRUE, use_gamma_submodel = TRUE, eps = 1e-8) {
    .Call(`_SGCB_fit_gg_natural_gradient_cpp`, X, n_iter, lr, weight_decay, use_natural_grad, use_firth_override, use_gamma_submodel, eps)
}

fit_gg_profile_init_cpp <- function(X, use_gamma_submodel = TRUE, min_gamma = 0.2, max_gamma = 5.0, eps = 1e-8) {
    .Call(`_SGCB_fit_gg_profile_init_cpp`, X, use_gamma_submodel, min_gamma, max_gamma, eps)
}

fit_gg_hierarchical_bayes_cpp <- function(X, n_iter = -1L, lr = -1, prior_strength = -1, use_natural_grad = TRUE, eps = 1e-8) {
    .Call(`_SGCB_fit_gg_hierarchical_bayes_cpp`, X, n_iter, lr, prior_strength, use_natural_grad, eps)
}

adaptive_squeeze_var_gg_informed_cpp <- function(vars, gg_alpha, gg_beta, gg_gamma, n_samples, eps = 1e-8) {
    .Call(`_SGCB_adaptive_squeeze_var_gg_informed_cpp`, vars, gg_alpha, gg_beta, gg_gamma, n_samples, eps)
}

adaptive_squeeze_var_hierarchical_cpp <- function(vars, gene_means, n_samples, use_rff_trend = FALSE, eps = 1e-8) {
    .Call(`_SGCB_adaptive_squeeze_var_hierarchical_cpp`, vars, gene_means, n_samples, use_rff_trend, eps)
}

manifold_distance_test_cpp <- function(alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, eps = 1e-8) {
    .Call(`_SGCB_manifold_distance_test_cpp`, alpha_ctrl, beta_ctrl, gamma_ctrl, alpha_treat, beta_treat, gamma_treat, n_ctrl, n_treat, eps)
}

sgcb_wls_ebayes_cpp <- function(y, design, contrast, gene_means, weights, eps = 1e-8) {
    .Call(`_SGCB_sgcb_wls_ebayes_cpp`, y, design, contrast, gene_means, weights, eps)
}

sgcb_info_geom_inference_cpp <- function(X, group, n_dropout = 50L, dropout_rate = 0.2, use_natural_grad = TRUE, use_hierarchical = TRUE, use_firth = TRUE, use_gamma_submodel = TRUE, use_gg_variance = TRUE, eps = 1e-8) {
    .Call(`_SGCB_sgcb_info_geom_inference_cpp`, X, group, n_dropout, dropout_rate, use_natural_grad, use_hierarchical, use_firth, use_gamma_submodel, use_gg_variance, eps)
}

